#Copyright (c)  WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: mgw-conf-mustache
  namespace: wso2-system
data:
  mgwConf.gotmpl: |

    #Copyright (c)  WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
    #
    # WSO2 Inc. licenses this file to you under the Apache License,
    # Version 2.0 (the "License"); you may not use this file except
    # in compliance with the License.
    # You may obtain a copy of the License at
    #
    # http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing,
    # software distributed under the License is distributed on an
    # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    # KIND, either express or implied.  See the License for the
    # specific language governing permissions and limitations
    # under the License.

    # Transport listener Configurations
    [listenerConfig]
      # Microgateway exposed IP / Host
      host = "0.0.0.0"
      # HTTP port that is used to make APIs available to the outside.
      httpPort = {{$.HttpPort}}
      # HTTPs port that is used to make APIs available to the outside and for endpoints(/token, /authorize, /revoke/, userinfo) of Key Manager.
      httpsPort = {{$.HttpsPort}}
      # HTTP port for endpoints(/token, /authorize, /revoke/, userinfo) of Key Manager
      tokenListenerPort = 9096
      # Internal keystore
      keyStorePath = "{{$.KeystorePath}}"
      keyStorePassword = "{{$.KeystorePassword}}"
      # Truststore
      trustStorePath = "{{$.TruststorePath}}"
      trustStorePassword = "{{$.TruststorePassword}}"

    # API Authorization security for the gateway and the backend
    [authConfig]
      # Authorization header expected by the Microgateway. Can be overridden at API level using the extension
      authorizationHeader = "Authorization"
      # Remove authorization header from the backend request
      removeAuthHeaderFromOutMessage = true

    # API JWT Authorization security for backend
    [jwtConfig]
      # JWT header when forwarding the request to the backend
      header = "{{$.JwtHeader}}"

    # Key manager configurations
    [keyManager]
      # Connection URL of the Key Manager server
      serverUrl = "{{$.KeyManagerServerUrl}}"
      # The token endpoint context of the Key Manager server
      tokenContext = "oauth2"
      # timestamp skew in seconds which added when checking the token validity period
      timestampSkew = 5000
      # External Key Manager
      external = false
      # Basic security configurations
      [keymanager.security.basic]
        enabled = true
        username = "{{$.KeyManagerUsername}}"
        password = "{{$.KeyManagerPassword}}"
      # Oauth2 security configurations
      [keymanager.security.oauth2]
        enabled = false
        # Authentication credentials should be sent via (AUTH_HEADER_BEARER/POST_BODY_BEARER/NO_BEARER)?
        credentialBearer = "AUTH_HEADER_BEARER"
        # Token URL for the authorization endpoint
        tokenUrl = ""
        # Oauth2 security grants
        [keymanager.security.oauth2.clientCredential]
          enabled = false
          clientId = ""
          clientSecret = ""
          scopes = ""
        [keymanager.security.oauth2.password]
          enabled = false
          clientId = ""
          clientSecret = ""
          scopes = ""
          username = ""
          password = ""
        [keymanager.security.oauth2.directToken]
          enabled = false
          accessToken = ""
        [keymanager.security.oauth2.refresh]
          enabled = false
          refreshUrl = ""
          scopes = ""
          refreshToken = ""
          clientId = ""
          clientSecret = ""


    # JWT token authorization configurations. You can provide multiple JWT issuers
    {{range .JwtConfigs}}
    [[jwtTokenConfig]]
      issuer = "{{.Issuer}}"
      {{ if .AudiencePresent }}
      audience = "{{.Audience}}"
      {{ end }}
      certificateAlias = "{{.CertificateAlias}}"
      # Validate subscribed APIs
      validateSubscription = {{.ValidateSubscription}}
    {{end}}

    # JWT token revocation configurations
    [tokenRevocationConfig]
    # Real time revocation configurations
      [tokenRevocationConfig.realtime]
        enableRealtimeMessageRetrieval = {{$.EnableRealtimeMessageRetrieval}}
        # The JMS Message Broker that identify messages related to revoked tokens
        jmsConnectionTopic = "tokenRevocation"
        # The message broker context factory
        jmsConnectioninitialContextFactory = "wso2mbInitialContextFactory"
        # The message broker connection URL
        jmsConnectionProviderUrl= "amqp://admin:admin@carbon/carbon?brokerlist='tcp://{{$.JmsConnectionProvider}}"
        # The username used to establish  the message broker connection
        jmsConnectionUsername = ""
        # The password used to establish  the message broker connection
        jmsConnectionPassword = ""
      # Persistent revocation configurations
      [tokenRevocationConfig.persistent]
        enablePersistentStorageRetrieval = false
        # Use etcd as the default persistent storage
        useDefault = true
        # The hostname of your persistent storage server (e.g.: <etcd-server-access-URL>/<service>/keys/jti/)
        hostname = "https://127.0.0.1:2379/v2/keys/jti/"
        # The username of your persistent storage server
        username = "root"
        # The password of your persistent storage server
        password = "root"

    # token cache configurations
    [caching]
      # Expiry time of the cache in seconds
      tokenCacheExpiryTime = 900000
      # The size of the cache in MB
      tokenCacheCapacity = 10000
      # The factor of the cache that will be cleared when the cache is full.
      tokenCacheEvictionFactor = 0.25

    # Analytics configurations
    [analytics]
      # The configured API Manager analytics stream version
      streamVersion = "3.2.0"
      # Configurations for file upload analytics
      [analytics.fileUpload]
        enable = {{$.AnalyticsEnabled}}
        # Time interval in milliseconds for file uploading task
        uploadingTimeSpanInMillis = {{$.UploadingTimeSpanInMillis}}
        # Initial time delay in milliseconds for file upload analytics
        initialDelayInMillis = 5000
        # Endpoint configured to accept file upload analytics
        uploadingEndpoint = "https://{{$.AnalyticsHostname}}:{{$.AnalyticsPort}}/analytics/v1.0/usage/upload-file"
        # File rotating period in milliseconds
        rotatingPeriod = {{$.RotatingPeriod}}
        # To enable file upload task
        taskUploadFiles = {{$.UploadFiles}}
        # Username used in analytics server
        username = "{{$.AnalyticsUsername}}"
        # Password used in in analytics server
        password = "{{$.AnalyticsPassword}}"
      [analytics.gRPCAnalytics]
        enable = false
        # APIM Analytics endpoint configured to accept gRPC analytics
        endpointURL = "https://localhost:9806"
        # Time interval in milliseconds for gRPC connection recovery task
        reconnectTimeInMillies = 6000

    # User configuration for Basic auth
    [b7a.users]
      [b7a.users.{{$.BasicUsername}}]
          # password should be sha1 encrypted by default
          password = "{{$.BasicPassword}}"

    # Request and response validation configurations
    [validationConfig]
      enableRequestValidation = {{$.EnableRequestValidation}}
      enableResponseValidation = {{$.EnableResponseValidation}}

    # Enable http2
    [http2]
      enable = true

    # HTTP client configuration
    [httpClients]
      # Hostname verification
      verifyHostname={{$.VerifyHostname}}

    # Mutual SSL configuration
    [mutualSSLConfig]
      # SSL Protocol to be used
      protocolName = "TLS"
      # SSL/TLS protocols to be enabled
      protocolVersions = "TLSv1.2,TLSv1.1"
      # List of ciphers to be used
      ciphers="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256  ,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256  ,TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
      # The type of client certificate verification. (e.g.: "require" or "optional")
      sslVerifyClient = "optional"

    # API Key authentication configurations
    {{range .APIKeyConfigs}}
    [apikey.tokenConfigs]
      issuer = "{{.APIKeyIssuer}}"
      certificateAlias = "{{.APIKeyCertificateAlias}}"
      audience = "{{.APIKeyAudience}}"
      # Validate Allowed/subscribed APIs
      validateAllowedAPIs = {{.ValidateAllowedAPIs}}
    {{end}}

    [apikey.issuer]
      # API Key STS token configurations
      [apikey.issuer.tokenConfig]
        enabled = {{$.EnabledAPIKeyIssuer}}
        keyStorePath = "{{$.APIKeyKeystorePath}}"
        keyStorePassword = "{{$.APIKeyKeystorePassword}}"
        issuer = "{{$.APIKeyIssuerName}}"
        certificateAlias = "{{$.APIKeyIssuerCertificateAlias}}"
        validityTime = {{$.ValidityTime}}
        {{range $allowedAPI := .APIKeyAllowedAPIs}}
          {{range $allowedAPIName, $allowedAPIVersions := $allowedAPI}}
        [[apikey.issuer.api]]
          name = "{{$allowedAPIName}}"
          versions = "{{$allowedAPIVersions}}"
          {{end}}
        {{end}}

    # JWT Generator configurations
    [jwtGeneratorConfig]
      # Enable jwt generator
      jwtGeneratorEnabled = {{$.EnabledJwtGenerator}}
      # Dialect prefix that can be added to the claims
      claimDialect = "{{$.JwtClaimDialect}}"
      # Signature algorithm used to sign the JWT token (only SHA256withRSA and NONE is supported)
      signingAlgorithm = "{{$.JwtSigningAlgorithm}}"
      # Certificate alias from the keystore
      certificateAlias = "{{$.JwtCertificateAlias}}"
      # Private key alias from the keystore
      privateKeyAlias = "{{$.JwtPrivateKeyAlias}}"
      # JWT token expiry time - ms (valid only if the jwt generator caching mechanism is disabled)
      tokenExpiry = {{$.JwtTokenExpiry}}
      # Restricted claims as an array that should not be included in the backend JWT token
      # Example: restrictedClaims=["claim1","claim2","claim3"]
      restrictedClaims = {{$.JwtRestrictedClaims}}
      # Token issuer standard claim
      issuer = "{{$.JwtIssuer}}"
      # Token audience standard claim
      audience = {{$.JwtAudience}}
      # JWT token generator implementation
      generatorImpl = "{{$.JwtGeneratorImpl}}"
      # JWT Generator cache configurations
      [jwtGeneratorConfig.jwtGeneratorCaching]
        # Enable jwt generator token caching
        tokenCacheEnable = {{$.JwtTokenCacheEnable}}
        # Token cache expiry time (ms)
        tokenCacheExpiryTime = {{$.JwtTokenCacheExpiryTime}}
        # Token cache capacity
        tokenCacheCapacity = {{$.JwtTokenCacheCapacity}}
        # Token cache eviction factor
        tokenCacheEvictionFactor = {{$.JwtTokenCacheEvictionFactor}}

    # Throttling configurations
    [throttlingConfig]

      # Connect with the central traffic manager
      enabledGlobalTMEventPublishing = {{$.EnabledGlobalTMEventPublishing}}
      # The message broker context factory
      jmsConnectioninitialContextFactory = "wso2mbInitialContextFactory"
      # The message broker connection URL
      jmsConnectionProviderUrl = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://{{$.JmsConnectionProvider}}?retries='100'&connectdelay='10000''"
      # The username used to establish  the message broker connection
      jmsConnectionUsername = ""
      # The password used to establish  the message broker connection
      jmsConnectionPassword = ""
      # The central traffic management solution URL
      throttleEndpointUrl = "https://{{$.ThrottleEndpoint}}/endpoints"
      # username:password to create the connection to the central traffic manager
      throttleEndpointbase64Header = "{{$.ApimUsername}}:{{$.ApimPassword}}"
      #Configurations related to retrieve custom throttle policy related key templates from traffic manager or key manager.
      [throttlingConfig.dataRetriever]
        serverUrl = "https://{{$.ThrottleEndpoint}}/internal/data/v1"
        username = "{{$.ApimUsername}}"
        password = "{{$.ApimPassword}}"

      [throttlingConfig.binary]
        enabled = true

        # Credentials required to establish connection between Traffic Manager
        username = "{{$.ApimUsername}}"
        password = "{{$.ApimPassword}}"
        # Receiver URL and the authentication URL of the Traffic manager node/nodes
        [[throttlingConfig.binary.URLGroup]]
          receiverURL = "tcp://{{$.ThrottlingRecieverURL}}"
          authURL = "ssl://{{$.ThrottlingAuthURL}}"
        # Data publisher object pool configurations
        [throttlingConfig.binary.publisherPool]
          maxIdle = 1000
          initIdleCapacity = 200
        # Data publisher thread pool configurations
        [throttlingConfig.binary.publisherThreadPool]
          corePoolSize = 200
          maxPoolSize = 1000
          keepAliveTime = 200
        [throttlingConfig.binary.agent]
          # SSL Protocols
          sslEnabledProtocols = "TLSv1,TLSv1.1,TLSv1.2"
          # ciphers
          ciphers="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256  ,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256  ,TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
          # The size of the queue event disruptor which handles events before they are published.
          # The value specified should always be the result of an exponent with 2 as the base.
          queueSize = 32768
          # The maximum number of events in a batch sent to the queue event disruptor at a given time
          batchSize = 200
          # The number of threads that will be reserved to handle events at the time you start
          corePoolSize = 1
          # Socket timeout
          socketTimeoutMS = 30000
          # The maximum number of threads that should be reserved at any given time to handle events
          maxPoolSize = 1
          # The amount of time which threads in excess of the core pool size may remain idle before being terminated.
          keepAliveTimeInPool = 20
          # The time interval between reconnection
          reconnectionInterval = 30
          # TCP connection pool configurations (for data publishing)
          maxTransportPoolSize = 250
          maxIdleConnections = 250
          evictionTimePeriod = 5500
          minIdleTimeInPool = 5000
          # SSL connection pool configurations (for authentication)
          secureMaxIdleTransportPoolSize = 250
          secureMaxIdleConnections = 250
          secureEvictionTimePeriod = 5500
          secureMinIdleTimeInPool = 5000

      # Configurations related to node local throttling.
      [throttlingConfig.nodeLocal]
        # Core number of threads in the thread pool.
        processThreadPoolCoreSize = 200
        # Maximum number of threads in the thread pool.
        processThreadPoolMaximumSize = 1000
        # Keep alive time of the threads in seconds
        processThreadPoolKeepAliveTime = 200
        # Throttle data cleanup task frequency in seconds.
        cleanUpFrequency = 3600

    # Configurations for retrieving API and subscription data from API Manager.
    [apim.eventHub]
      # Enable/ Disable the feature
      enable = {{$.EnabledEventhub}}
      # The API Manager URL
      serviceUrl = "https://{{$.ThrottleEndpoint}}"
      # The internal data REST API context.
      internalDataContext="/internal/data/v1/"
      # User name and password of the internal data api.
      username = "{{$.ApimUsername}}"
      password = "{{$.ApimPassword}}"
      # The message broker connection URL.
      eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://{{$.JmsConnectionProvider}}'"

    # ballerina logs
    [b7a.log]
      level="{{$.LogLevel}}"

    {{ if .ObservabilityEnabled }}
    # ballerina metrics
    [b7a.observability.metrics]
      # Flag to enable Metrics
      enabled = true
      reporter = "prometheus"

    # ballerina metrics for prometheus
    [b7a.observability.metrics.prometheus]
      port=9797
    {{ end }}