apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-with-analytics-mysql-deployment
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: wso2apim-with-analytics-mysql
      product: wso2am
  template:
    metadata:
      labels:
        deployment: wso2apim-with-analytics-mysql
        product: wso2am
    spec:
      containers:
        - name: wso2apim-with-analytics-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: wso2carbon
            - name: MYSQL_PASSWORD
              value: wso2carbon
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-dbscripts
              mountPath: /docker-entrypoint-initdb.d
          args: ['--max-connections', '10000']
      volumes:
        - name: mysql-dbscripts
          configMap:
            name: mysql-dbscripts
